model: yolov5n-cls.pt
data: ../yolov5/dataset/medicine
epochs: 50
batch_size: 8
imgsz: 320
nosave: false
cache: null
device: ''
workers: 8
project: runs/train-cls
name: exp
exist_ok: false
pretrained: weights/yolov5n-cls.pt
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: runs/train-cls/exp9
